services:
  - type: web
    name: gfinhub
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ALPACA_KEY
        sync: false
      - key: ALPACA_SECRET
        sync: false
      - key: ALPACA_MODE
        value: paper
      - key: NODE_ENV
        value: production
